apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: traefik
spec:
  dnsNames:
    - {{ .Values.argocd.ingress.host }}
  secretName: argocd-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
